enabled: true  # Habilita/desactiva OpenRouter
api_key: "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
"
endpoint: "https://openrouter.ai/api/v1"
model: "openai/gpt-4o-mini"
max_tokens: 1000
temperature: 0.7