version: '3.8'
services:
  corec:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=corec_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_password}
      - REDIS_USERNAME=corec_user
      - REDIS_PASSWORD=${REDIS_PASSWORD:-secure_password}
    depends_on:
      - redis
      - postgres
    volumes:
      - ./configs:/app/configs
    networks:
      - corec-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A corec.core.celery_app worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=corec_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_password}
      - REDIS_USERNAME=corec_user
      - REDIS_PASSWORD=${REDIS_PASSWORD:-secure_password}
    depends_on:
      - redis
      - postgres
    networks:
      - corec-net

  redis:
    image: redis:7.0
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-secure_password}
    volumes:
      - redis-data:/data
    networks:
      - corec-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=corec_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - corec-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - corec-net
    ports:
      - "9090:9090"

networks:
  corec-net:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
  prometheus-data: